// Copyright (c) 2015-present Mattermost, Inc. All Rights Reserved.
// See LICENSE.txt for license information.

import keyMirror from 'mattermost-redux/utils/key_mirror';

export default keyMirror({
    // System
    AI_HEALTH_CHECK_REQUEST: null,
    AI_HEALTH_CHECK_SUCCESS: null,
    AI_HEALTH_CHECK_FAILURE: null,

    // Summaries
    AI_SUMMARY_REQUEST: null,
    AI_SUMMARY_SUCCESS: null,
    AI_SUMMARY_FAILURE: null,
    AI_SUMMARIES_BY_CHANNEL_REQUEST: null,
    AI_SUMMARIES_BY_CHANNEL_SUCCESS: null,
    AI_SUMMARIES_BY_CHANNEL_FAILURE: null,
    AI_SUMMARIZE_THREAD_REQUEST: null,
    AI_SUMMARIZE_THREAD_SUCCESS: null,
    AI_SUMMARIZE_THREAD_FAILURE: null,
    AI_SUMMARIZE_CHANNEL_REQUEST: null,
    AI_SUMMARIZE_CHANNEL_SUCCESS: null,
    AI_SUMMARIZE_CHANNEL_FAILURE: null,
    AI_CLEAR_SUMMARY: null,
    AI_SET_SUMMARY_LEVEL: null,

    // Action Items
    GET_ACTION_ITEMS_REQUEST: null,
    GET_ACTION_ITEMS_SUCCESS: null,
    GET_ACTION_ITEMS_FAILURE: null,
    GET_ACTION_ITEM_REQUEST: null,
    GET_ACTION_ITEM_SUCCESS: null,
    GET_ACTION_ITEM_FAILURE: null,
    CREATE_ACTION_ITEM_REQUEST: null,
    CREATE_ACTION_ITEM_SUCCESS: null,
    CREATE_ACTION_ITEM_FAILURE: null,
    UPDATE_ACTION_ITEM_REQUEST: null,
    UPDATE_ACTION_ITEM_SUCCESS: null,
    UPDATE_ACTION_ITEM_FAILURE: null,
    COMPLETE_ACTION_ITEM_REQUEST: null,
    COMPLETE_ACTION_ITEM_SUCCESS: null,
    COMPLETE_ACTION_ITEM_FAILURE: null,
    DELETE_ACTION_ITEM_REQUEST: null,
    DELETE_ACTION_ITEM_SUCCESS: null,
    DELETE_ACTION_ITEM_FAILURE: null,
    GET_ACTION_ITEM_STATS_REQUEST: null,
    GET_ACTION_ITEM_STATS_SUCCESS: null,
    GET_ACTION_ITEM_STATS_FAILURE: null,

    // Analytics
    AI_ANALYTICS_REQUEST: null,
    AI_ANALYTICS_SUCCESS: null,
    AI_ANALYTICS_FAILURE: null,

    // Message Formatting
    AI_FORMAT_MESSAGE_REQUEST: null,
    AI_FORMAT_MESSAGE_SUCCESS: null,
    AI_FORMAT_MESSAGE_FAILURE: null,

    // Preferences
    AI_PREFERENCES_GET_REQUEST: null,
    AI_PREFERENCES_GET_SUCCESS: null,
    AI_PREFERENCES_GET_FAILURE: null,
    AI_PREFERENCES_UPDATE_REQUEST: null,
    AI_PREFERENCES_UPDATE_SUCCESS: null,
    AI_PREFERENCES_UPDATE_FAILURE: null,
});

export const AIActionItemsTypes = keyMirror({
    GET_ACTION_ITEMS_REQUEST: null,
    GET_ACTION_ITEMS_SUCCESS: null,
    GET_ACTION_ITEMS_FAILURE: null,
    GET_ACTION_ITEM_REQUEST: null,
    GET_ACTION_ITEM_SUCCESS: null,
    GET_ACTION_ITEM_FAILURE: null,
    CREATE_ACTION_ITEM_REQUEST: null,
    CREATE_ACTION_ITEM_SUCCESS: null,
    CREATE_ACTION_ITEM_FAILURE: null,
    UPDATE_ACTION_ITEM_REQUEST: null,
    UPDATE_ACTION_ITEM_SUCCESS: null,
    UPDATE_ACTION_ITEM_FAILURE: null,
    COMPLETE_ACTION_ITEM_REQUEST: null,
    COMPLETE_ACTION_ITEM_SUCCESS: null,
    COMPLETE_ACTION_ITEM_FAILURE: null,
    DELETE_ACTION_ITEM_REQUEST: null,
    DELETE_ACTION_ITEM_SUCCESS: null,
    DELETE_ACTION_ITEM_FAILURE: null,
    GET_ACTION_ITEM_STATS_REQUEST: null,
    GET_ACTION_ITEM_STATS_SUCCESS: null,
    GET_ACTION_ITEM_STATS_FAILURE: null,
});
