// Copyright (c) 2015-present Mattermost, Inc. All Rights Reserved.
// See LICENSE.txt for license information.

import keyMirror from 'mattermost-redux/utils/key_mirror';

export default keyMirror({
    // System
    AI_HEALTH_CHECK_REQUEST: null,
    AI_HEALTH_CHECK_SUCCESS: null,
    AI_HEALTH_CHECK_FAILURE: null,

    // Summaries
    AI_SUMMARY_REQUEST: null,
    AI_SUMMARY_SUCCESS: null,
    AI_SUMMARY_FAILURE: null,
    AI_SUMMARIES_BY_CHANNEL_REQUEST: null,
    AI_SUMMARIES_BY_CHANNEL_SUCCESS: null,
    AI_SUMMARIES_BY_CHANNEL_FAILURE: null,
    AI_SUMMARIZE_THREAD_REQUEST: null,
    AI_SUMMARIZE_THREAD_SUCCESS: null,
    AI_SUMMARIZE_THREAD_FAILURE: null,
    AI_SUMMARIZE_CHANNEL_REQUEST: null,
    AI_SUMMARIZE_CHANNEL_SUCCESS: null,
    AI_SUMMARIZE_CHANNEL_FAILURE: null,
    AI_CLEAR_SUMMARY: null,
    AI_SET_SUMMARY_LEVEL: null,

    // Action Items
    AI_ACTION_ITEM_CREATE_REQUEST: null,
    AI_ACTION_ITEM_CREATE_SUCCESS: null,
    AI_ACTION_ITEM_CREATE_FAILURE: null,
    AI_ACTION_ITEM_GET_REQUEST: null,
    AI_ACTION_ITEM_GET_SUCCESS: null,
    AI_ACTION_ITEM_GET_FAILURE: null,
    AI_ACTION_ITEMS_BY_USER_REQUEST: null,
    AI_ACTION_ITEMS_BY_USER_SUCCESS: null,
    AI_ACTION_ITEMS_BY_USER_FAILURE: null,
    AI_ACTION_ITEMS_BY_CHANNEL_REQUEST: null,
    AI_ACTION_ITEMS_BY_CHANNEL_SUCCESS: null,
    AI_ACTION_ITEMS_BY_CHANNEL_FAILURE: null,
    AI_ACTION_ITEM_UPDATE_REQUEST: null,
    AI_ACTION_ITEM_UPDATE_SUCCESS: null,
    AI_ACTION_ITEM_UPDATE_FAILURE: null,
    AI_ACTION_ITEM_DELETE_REQUEST: null,
    AI_ACTION_ITEM_DELETE_SUCCESS: null,
    AI_ACTION_ITEM_DELETE_FAILURE: null,

    // Analytics
    AI_ANALYTICS_REQUEST: null,
    AI_ANALYTICS_SUCCESS: null,
    AI_ANALYTICS_FAILURE: null,

    // Message Formatting
    AI_FORMAT_MESSAGE_REQUEST: null,
    AI_FORMAT_MESSAGE_SUCCESS: null,
    AI_FORMAT_MESSAGE_FAILURE: null,

    // Preferences
    AI_PREFERENCES_GET_REQUEST: null,
    AI_PREFERENCES_GET_SUCCESS: null,
    AI_PREFERENCES_GET_FAILURE: null,
    AI_PREFERENCES_UPDATE_REQUEST: null,
    AI_PREFERENCES_UPDATE_SUCCESS: null,
    AI_PREFERENCES_UPDATE_FAILURE: null,
});

