ALTER TABLE AIPreferences
ADD COLUMN IF NOT EXISTS EnableLinkSummaries BOOLEAN DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS AutoSummarizeLinks BOOLEAN DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS DefaultLinkExpanded BOOLEAN DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS LinkSummaryLength VARCHAR(16) DEFAULT 'standard';

