// Code generated by mockery v2.53.4. DO NOT EDIT.

package mocks

import (
	model "github.com/mattermost/mattermost/server/public/model"
	mock "github.com/stretchr/testify/mock"
)

// AIAnalyticsStore is an autogenerated mock type for the AIAnalyticsStore type
type AIAnalyticsStore struct {
	mock.Mock
}

// DeleteOlderThan provides a mock function with given fields: date
func (_m *AIAnalyticsStore) DeleteOlderThan(date string) (int64, error) {
	ret := _m.Called(date)

	if len(ret) == 0 {
		panic("no return value specified for DeleteOlderThan")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (int64, error)); ok {
		return rf(date)
	}
	if rf, ok := ret.Get(0).(func(string) int64); ok {
		r0 = rf(date)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(date)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Get provides a mock function with given fields: id
func (_m *AIAnalyticsStore) Get(id string) (*model.AIAnalytics, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *model.AIAnalytics
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*model.AIAnalytics, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(string) *model.AIAnalytics); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.AIAnalytics)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByChannel provides a mock function with given fields: channelId, startDate, endDate
func (_m *AIAnalyticsStore) GetByChannel(channelId string, startDate string, endDate string) ([]*model.AIAnalytics, error) {
	ret := _m.Called(channelId, startDate, endDate)

	if len(ret) == 0 {
		panic("no return value specified for GetByChannel")
	}

	var r0 []*model.AIAnalytics
	var r1 error
	if rf, ok := ret.Get(0).(func(string, string, string) ([]*model.AIAnalytics, error)); ok {
		return rf(channelId, startDate, endDate)
	}
	if rf, ok := ret.Get(0).(func(string, string, string) []*model.AIAnalytics); ok {
		r0 = rf(channelId, startDate, endDate)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.AIAnalytics)
		}
	}

	if rf, ok := ret.Get(1).(func(string, string, string) error); ok {
		r1 = rf(channelId, startDate, endDate)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByChannelAndDate provides a mock function with given fields: channelId, date
func (_m *AIAnalyticsStore) GetByChannelAndDate(channelId string, date string) (*model.AIAnalytics, error) {
	ret := _m.Called(channelId, date)

	if len(ret) == 0 {
		panic("no return value specified for GetByChannelAndDate")
	}

	var r0 *model.AIAnalytics
	var r1 error
	if rf, ok := ret.Get(0).(func(string, string) (*model.AIAnalytics, error)); ok {
		return rf(channelId, date)
	}
	if rf, ok := ret.Get(0).(func(string, string) *model.AIAnalytics); ok {
		r0 = rf(channelId, date)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.AIAnalytics)
		}
	}

	if rf, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = rf(channelId, date)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Save provides a mock function with given fields: analytics
func (_m *AIAnalyticsStore) Save(analytics *model.AIAnalytics) (*model.AIAnalytics, error) {
	ret := _m.Called(analytics)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 *model.AIAnalytics
	var r1 error
	if rf, ok := ret.Get(0).(func(*model.AIAnalytics) (*model.AIAnalytics, error)); ok {
		return rf(analytics)
	}
	if rf, ok := ret.Get(0).(func(*model.AIAnalytics) *model.AIAnalytics); ok {
		r0 = rf(analytics)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.AIAnalytics)
		}
	}

	if rf, ok := ret.Get(1).(func(*model.AIAnalytics) error); ok {
		r1 = rf(analytics)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: analytics
func (_m *AIAnalyticsStore) Update(analytics *model.AIAnalytics) (*model.AIAnalytics, error) {
	ret := _m.Called(analytics)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 *model.AIAnalytics
	var r1 error
	if rf, ok := ret.Get(0).(func(*model.AIAnalytics) (*model.AIAnalytics, error)); ok {
		return rf(analytics)
	}
	if rf, ok := ret.Get(0).(func(*model.AIAnalytics) *model.AIAnalytics); ok {
		r0 = rf(analytics)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.AIAnalytics)
		}
	}

	if rf, ok := ret.Get(1).(func(*model.AIAnalytics) error); ok {
		r1 = rf(analytics)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewAIAnalyticsStore creates a new instance of AIAnalyticsStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAIAnalyticsStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *AIAnalyticsStore {
	mock := &AIAnalyticsStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
