// Code generated by mockery v2.53.4. DO NOT EDIT.

package mocks

import (
	model "github.com/mattermost/mattermost/server/public/model"
	mock "github.com/stretchr/testify/mock"
)

// AIActionItemStore is an autogenerated mock type for the AIActionItemStore type
type AIActionItemStore struct {
	mock.Mock
}

// Delete provides a mock function with given fields: id, deleteAt
func (_m *AIActionItemStore) Delete(id string, deleteAt int64) error {
	ret := _m.Called(id, deleteAt)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, int64) error); ok {
		r0 = rf(id, deleteAt)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Get provides a mock function with given fields: id
func (_m *AIActionItemStore) Get(id string) (*model.AIActionItem, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *model.AIActionItem
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*model.AIActionItem, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(string) *model.AIActionItem); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.AIActionItem)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByAssignee provides a mock function with given fields: assigneeId, offset, limit
func (_m *AIActionItemStore) GetByAssignee(assigneeId string, offset int, limit int) ([]*model.AIActionItem, error) {
	ret := _m.Called(assigneeId, offset, limit)

	if len(ret) == 0 {
		panic("no return value specified for GetByAssignee")
	}

	var r0 []*model.AIActionItem
	var r1 error
	if rf, ok := ret.Get(0).(func(string, int, int) ([]*model.AIActionItem, error)); ok {
		return rf(assigneeId, offset, limit)
	}
	if rf, ok := ret.Get(0).(func(string, int, int) []*model.AIActionItem); ok {
		r0 = rf(assigneeId, offset, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.AIActionItem)
		}
	}

	if rf, ok := ret.Get(1).(func(string, int, int) error); ok {
		r1 = rf(assigneeId, offset, limit)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByChannel provides a mock function with given fields: channelId, offset, limit
func (_m *AIActionItemStore) GetByChannel(channelId string, offset int, limit int) ([]*model.AIActionItem, error) {
	ret := _m.Called(channelId, offset, limit)

	if len(ret) == 0 {
		panic("no return value specified for GetByChannel")
	}

	var r0 []*model.AIActionItem
	var r1 error
	if rf, ok := ret.Get(0).(func(string, int, int) ([]*model.AIActionItem, error)); ok {
		return rf(channelId, offset, limit)
	}
	if rf, ok := ret.Get(0).(func(string, int, int) []*model.AIActionItem); ok {
		r0 = rf(channelId, offset, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.AIActionItem)
		}
	}

	if rf, ok := ret.Get(1).(func(string, int, int) error); ok {
		r1 = rf(channelId, offset, limit)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByUser provides a mock function with given fields: userId, offset, limit
func (_m *AIActionItemStore) GetByUser(userId string, offset int, limit int) ([]*model.AIActionItem, error) {
	ret := _m.Called(userId, offset, limit)

	if len(ret) == 0 {
		panic("no return value specified for GetByUser")
	}

	var r0 []*model.AIActionItem
	var r1 error
	if rf, ok := ret.Get(0).(func(string, int, int) ([]*model.AIActionItem, error)); ok {
		return rf(userId, offset, limit)
	}
	if rf, ok := ret.Get(0).(func(string, int, int) []*model.AIActionItem); ok {
		r0 = rf(userId, offset, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.AIActionItem)
		}
	}

	if rf, ok := ret.Get(1).(func(string, int, int) error); ok {
		r1 = rf(userId, offset, limit)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetPendingReminders provides a mock function with given fields: currentTime
func (_m *AIActionItemStore) GetPendingReminders(currentTime int64) ([]*model.AIActionItem, error) {
	ret := _m.Called(currentTime)

	if len(ret) == 0 {
		panic("no return value specified for GetPendingReminders")
	}

	var r0 []*model.AIActionItem
	var r1 error
	if rf, ok := ret.Get(0).(func(int64) ([]*model.AIActionItem, error)); ok {
		return rf(currentTime)
	}
	if rf, ok := ret.Get(0).(func(int64) []*model.AIActionItem); ok {
		r0 = rf(currentTime)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.AIActionItem)
		}
	}

	if rf, ok := ret.Get(1).(func(int64) error); ok {
		r1 = rf(currentTime)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// PermanentDelete provides a mock function with given fields: id
func (_m *AIActionItemStore) PermanentDelete(id string) error {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for PermanentDelete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Save provides a mock function with given fields: actionItem
func (_m *AIActionItemStore) Save(actionItem *model.AIActionItem) (*model.AIActionItem, error) {
	ret := _m.Called(actionItem)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 *model.AIActionItem
	var r1 error
	if rf, ok := ret.Get(0).(func(*model.AIActionItem) (*model.AIActionItem, error)); ok {
		return rf(actionItem)
	}
	if rf, ok := ret.Get(0).(func(*model.AIActionItem) *model.AIActionItem); ok {
		r0 = rf(actionItem)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.AIActionItem)
		}
	}

	if rf, ok := ret.Get(1).(func(*model.AIActionItem) error); ok {
		r1 = rf(actionItem)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: actionItem
func (_m *AIActionItemStore) Update(actionItem *model.AIActionItem) (*model.AIActionItem, error) {
	ret := _m.Called(actionItem)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 *model.AIActionItem
	var r1 error
	if rf, ok := ret.Get(0).(func(*model.AIActionItem) (*model.AIActionItem, error)); ok {
		return rf(actionItem)
	}
	if rf, ok := ret.Get(0).(func(*model.AIActionItem) *model.AIActionItem); ok {
		r0 = rf(actionItem)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.AIActionItem)
		}
	}

	if rf, ok := ret.Get(1).(func(*model.AIActionItem) error); ok {
		r1 = rf(actionItem)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewAIActionItemStore creates a new instance of AIActionItemStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAIActionItemStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *AIActionItemStore {
	mock := &AIActionItemStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
