// Code generated by mockery v2.53.4. DO NOT EDIT.

package mocks

import (
	model "github.com/mattermost/mattermost/server/public/model"
	mock "github.com/stretchr/testify/mock"
)

// AIPreferencesStore is an autogenerated mock type for the AIPreferencesStore type
type AIPreferencesStore struct {
	mock.Mock
}

// Delete provides a mock function with given fields: userId
func (_m *AIPreferencesStore) Delete(userId string) error {
	ret := _m.Called(userId)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(userId)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Get provides a mock function with given fields: id
func (_m *AIPreferencesStore) Get(id string) (*model.AIPreferences, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *model.AIPreferences
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*model.AIPreferences, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(string) *model.AIPreferences); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.AIPreferences)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByUser provides a mock function with given fields: userId
func (_m *AIPreferencesStore) GetByUser(userId string) (*model.AIPreferences, error) {
	ret := _m.Called(userId)

	if len(ret) == 0 {
		panic("no return value specified for GetByUser")
	}

	var r0 *model.AIPreferences
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*model.AIPreferences, error)); ok {
		return rf(userId)
	}
	if rf, ok := ret.Get(0).(func(string) *model.AIPreferences); ok {
		r0 = rf(userId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.AIPreferences)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(userId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Save provides a mock function with given fields: preferences
func (_m *AIPreferencesStore) Save(preferences *model.AIPreferences) (*model.AIPreferences, error) {
	ret := _m.Called(preferences)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 *model.AIPreferences
	var r1 error
	if rf, ok := ret.Get(0).(func(*model.AIPreferences) (*model.AIPreferences, error)); ok {
		return rf(preferences)
	}
	if rf, ok := ret.Get(0).(func(*model.AIPreferences) *model.AIPreferences); ok {
		r0 = rf(preferences)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.AIPreferences)
		}
	}

	if rf, ok := ret.Get(1).(func(*model.AIPreferences) error); ok {
		r1 = rf(preferences)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: preferences
func (_m *AIPreferencesStore) Update(preferences *model.AIPreferences) (*model.AIPreferences, error) {
	ret := _m.Called(preferences)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 *model.AIPreferences
	var r1 error
	if rf, ok := ret.Get(0).(func(*model.AIPreferences) (*model.AIPreferences, error)); ok {
		return rf(preferences)
	}
	if rf, ok := ret.Get(0).(func(*model.AIPreferences) *model.AIPreferences); ok {
		r0 = rf(preferences)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.AIPreferences)
		}
	}

	if rf, ok := ret.Get(1).(func(*model.AIPreferences) error); ok {
		r1 = rf(preferences)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewAIPreferencesStore creates a new instance of AIPreferencesStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAIPreferencesStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *AIPreferencesStore {
	mock := &AIPreferencesStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
