// Code generated by mockery v2.53.4. DO NOT EDIT.

package mocks

import (
	model "github.com/mattermost/mattermost/server/public/model"
	mock "github.com/stretchr/testify/mock"
)

// AISummaryStore is an autogenerated mock type for the AISummaryStore type
type AISummaryStore struct {
	mock.Mock
}

// Delete provides a mock function with given fields: id
func (_m *AISummaryStore) Delete(id string) error {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteExpired provides a mock function with given fields: currentTime
func (_m *AISummaryStore) DeleteExpired(currentTime int64) (int64, error) {
	ret := _m.Called(currentTime)

	if len(ret) == 0 {
		panic("no return value specified for DeleteExpired")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(int64) (int64, error)); ok {
		return rf(currentTime)
	}
	if rf, ok := ret.Get(0).(func(int64) int64); ok {
		r0 = rf(currentTime)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(int64) error); ok {
		r1 = rf(currentTime)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Get provides a mock function with given fields: id
func (_m *AISummaryStore) Get(id string) (*model.AISummary, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *model.AISummary
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*model.AISummary, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(string) *model.AISummary); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.AISummary)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByChannel provides a mock function with given fields: channelId, offset, limit
func (_m *AISummaryStore) GetByChannel(channelId string, offset int, limit int) ([]*model.AISummary, error) {
	ret := _m.Called(channelId, offset, limit)

	if len(ret) == 0 {
		panic("no return value specified for GetByChannel")
	}

	var r0 []*model.AISummary
	var r1 error
	if rf, ok := ret.Get(0).(func(string, int, int) ([]*model.AISummary, error)); ok {
		return rf(channelId, offset, limit)
	}
	if rf, ok := ret.Get(0).(func(string, int, int) []*model.AISummary); ok {
		r0 = rf(channelId, offset, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.AISummary)
		}
	}

	if rf, ok := ret.Get(1).(func(string, int, int) error); ok {
		r1 = rf(channelId, offset, limit)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetCachedSummary provides a mock function with given fields: channelId, summaryType, startTime, endTime
func (_m *AISummaryStore) GetCachedSummary(channelId string, summaryType string, startTime int64, endTime int64) (*model.AISummary, error) {
	ret := _m.Called(channelId, summaryType, startTime, endTime)

	if len(ret) == 0 {
		panic("no return value specified for GetCachedSummary")
	}

	var r0 *model.AISummary
	var r1 error
	if rf, ok := ret.Get(0).(func(string, string, int64, int64) (*model.AISummary, error)); ok {
		return rf(channelId, summaryType, startTime, endTime)
	}
	if rf, ok := ret.Get(0).(func(string, string, int64, int64) *model.AISummary); ok {
		r0 = rf(channelId, summaryType, startTime, endTime)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.AISummary)
		}
	}

	if rf, ok := ret.Get(1).(func(string, string, int64, int64) error); ok {
		r1 = rf(channelId, summaryType, startTime, endTime)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Save provides a mock function with given fields: summary
func (_m *AISummaryStore) Save(summary *model.AISummary) (*model.AISummary, error) {
	ret := _m.Called(summary)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 *model.AISummary
	var r1 error
	if rf, ok := ret.Get(0).(func(*model.AISummary) (*model.AISummary, error)); ok {
		return rf(summary)
	}
	if rf, ok := ret.Get(0).(func(*model.AISummary) *model.AISummary); ok {
		r0 = rf(summary)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.AISummary)
		}
	}

	if rf, ok := ret.Get(1).(func(*model.AISummary) error); ok {
		r1 = rf(summary)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewAISummaryStore creates a new instance of AISummaryStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAISummaryStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *AISummaryStore {
	mock := &AISummaryStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
